/* eslint-disable prettier/prettier */
// prettier-ignore
const translation = {
  "Global": {
    "Enter": "Masuk",
    "Submit": "Hantar",
    "NoneYet!": "Belum ada lagi!",
    "Cancel": "Batal",
    "Confirm": "Sahkan",
    "Accept": "Terima",
    "Reject": "Tolak",
    "Share": "Kongsi",
    "Decline": "Tolak",
    "Back": "Balik",
    "Next": "Seterusnya",
    "Continue": "Teruskan",
    "Info": "Maklumat",
    "ThisDecisionCannotBeChanged.": "Keputusan ini tidak boleh diubah.",
    "Failure": "Kegagalan",
    "Success": "Kejayaan",
    "SomethingWentWrong": "Ada yang tidak kena",
    "Done": "Selesai",
    "Skip": "Langkau",
    "View": "Lihat",
    "Home": "Rumah",
    "ErrorCode": "Kod salah",
    "Okay": "Baik",
    "GoBack": "Pergi balik",
    "GetStarted": "Mulakan",
    "Dismiss": "Tolak",
    "ShowDetails": "Tunjukkan Butiran",
    "TryAgain": "Cuba lagi",
    "Biometrics": "Biometrik",
    "On" : "Hidup",
    "Off": "Mati",
  },
  "Language": {
    "English": "Inggeris",
    "Melayu": "Melayu",
    "Chinese": "Chinese",
  },
  "Error": {
    "Unknown": "Ralat tidak diketahui",
    "Problem": "Masalah Telah Berlaku",
    "ErrorCode": "Kod salah",
    "Title1024": "Tidak Dapat Menerima Tawaran Kelayakan.",
    "Message1024": "Terdapat masalah semasa menerima Tawaran Kelayakan.",
    "Title1025": "Tidak Dapat Menolak Tawaran Kelayakan",
    "Message1025": "Terdapat masalah semasa Menolak Tawaran Kelayakan",
    "Title1026": "Tidak dapat mengemas kini Bukti Kelayakan Diperoleh.",
    "Message1026": "Terdapat masalah semasa mengemas kini Bukti Kelayakan Diperoleh.",
    "Title1027": "Tidak Dapat Menerima Permintaan Bukti.",
    "Message1027": "Terdapat masalah semasa menerima Permintaan Bukti.",
    "Title1028": "Tidak Dapat Menolak Permintaan Bukti",
    "Message1028": "Terdapat masalah semasa Menolak Permintaan Bukti",
    "Title1029": "Butiran Tidak Dapat Mengemas kini Bukti Kelayakan Yang Diperoleh.",
    "Message1029": "Terdapat masalah semasa mengemas kini Bukti Kelayakan Diperoleh.",
    "Title1030": "Tidak Dapat Menerima Sambungan.",
    "Message1030": "Terdapat masalah semasa menerima Pengalihan Sambungan.",
    "Title1031": "Tidak Dapat Menerima Sambungan.",
    "Message1031": "Terdapat masalah semasa Menerima Sambungan.",
    "Title1032": "Tidak dapat mengalih keluar Bukti kelayakan.",
    "Message1032": "Terdapat masalah semasa Mengalih Keluar Bukti Kelayakan.",
    "Title1033": "Tidak Dapat Mengambil Bukti Kelayakan.",
    "Message1033": "Bukti kelayakan tidak ditemui.",
    "Title1034": "Tidak dapat mengambil Permintaan Bukti.",
    "Message1034": "Permintaan Bukti tidak dapat ditemui.",
    "Title1035": "Tidak dapat mengambil Tawaran Kelayakan.",
    "Message1035": "Tawaran Bukti Kelayakan tidak dapat ditemui.",
    "Title1036": "Tidak dapat mengambil Bukti Kelayakan Wallet",
    "Message1036": "Bukti kelayakan Wallet tidak dapat ditemui",
  },
  "StatusMessages": {
    "InitAgent": "Ejen Permulaan .."
  },
  "Terms": {
    "TermsOfService": "Syarat Perkhidmatan",
    "TermsOfServiceText": ".",
    "IAgree": "Saya setuju",
    "Attestation": "Saya telah membaca, memahami dan menerima Terma dan Syarat.",
  },
  "PrivacyPolicy": {
    "Title": "Dasar Privasi",
    "CameraDisclosure": "Kamera digunakan untuk mengimbas Kod QR untuk pemprosesan segera pada peranti. Tiada maklumat tentang imej disimpan, digunakan untuk analitis atau dikongsi.",
  },
  "PinCreate": {
    "Message": {
      "CrossPatternValidation": 'Corak silang telah dikesan dalam PIN anda. Sila cuba lagi.',
      "OddOrEvenSequenceValidation": 'Urutan ganjil atau genap telah dikesan dalam PIN anda. Sila cuba lagi.',
      "NoRepetitionOfTheSameNumbersValidation":
        "PIN tidak boleh mempunyai pengulangan digit yang sama. Sila cuba lagi.",
      "NoRepetitionOfTheTwoSameNumbersValidation": 'Urutan dua digit berulang telah dikesan dalam PIN anda. Sila cuba lagi.',
      "NoSeriesOfNumbersValidation": 'Satu siri telah dikesan dalam PIN anda. Sila cuba lagi.',
      "PinOnlyContainDigitsValidation": 'PIN anda hanya perlu mengandungi digit. Sila cuba lagi.',
      "PinTooShortValidation": 'PIN anda terlalu pendek. Sila cuba lagi.',
      "PinTooLongValidation": 'PIN anda terlalu panjang. Sila cuba lagi.',
    },
    "Helper": {
      "CrossPatternValidation": 'Tidak mengandungi corak silang.',
      "OddOrEvenSequenceValidation": 'Tidak mengandungi urutan ganjil atau genap.',
      "NoRepetitionOfTheSameNumbersValidation": 'Tidak mengandungi nombor berulang yang sama.',
      "NoRepetitionOfTheTwoSameNumbersValidation": 'Tidak mengandungi urutan dua digit berulang.',
      "NoSeriesOfNumbersValidation": 'Tidak mengandungi siri nombor (123).',
      "PinOnlyContainDigitsValidation": 'Mesti mengandungi digit sahaja.',
      "PinTooShortValidation": 'PIN cukup panjang.',
      "PinTooLongValidation": 'PIN cukup panjang.',
    },
    "UserAuthenticationPIN": "PIN pengesahan pengguna",
    "PINTooShort": "PIN terlalu pendek",
    "InvalidPIN": "PIN tidak sah",
    "PINsDoNotMatch": "PIN Tidak Padan",
    "PleaseUseOnlyNumbersInYourPIN": "Sila gunakan nombor sahaja dalam PIN anda",
    "YourPINMustBe6DigitsInLength": "PIN anda perlu 6 digit panjang.",
    "EnteredPINsDoNotMatch": "PIN yang dimasukkan tidak sepadan. Sila cuba lagi.",
    "YouNeedToCreateA6DigitPIN": "Anda perlu membuat PIN 6 digit",
    "PleaseReenterYourPIN": "Sila masukkan semula PIN anda",
    "EnterPINTitle": "Masukkan PIN 6 digit",
    "EnterPIN": "Masukkan PIN",
    "ReenterPIN": "Sahkan PIN",
    "ReenterPINTitle": "Masukkan semula PIN",
    "CreatePIN": "Buat PIN",
    "RememberPIN": "Ingat PIN anda.",
    "PINDisclaimer": "Jika anda terlupa, anda perlu menyediakan dompet anda sekali lagi dan menambah semula kad anda.",
    "Show": "Tunjukkan PIN",
    "Hide": "Sembunyikan PIN",
    "ChangePIN": "Tukar PIN",
    "Continue": "Teruskan",
    "EnterYourCurrentPIN": "Masukkan PIN semasa anda"
  },
  "PinEnter": {
    "EnterPIN": "Masukkan PIN dompet anda",
    "Unlock": "Buka kunci",
    "Or": "Ataupun",
    "BiometricsUnlock": "Buka kunci dengan Biometrik",
    "IncorrectPIN": "PIN salah",
    "RepeatPIN": "Sila masukkan semula PIN anda.",
    "EnableBiometrics": "Anda perlu mendayakan biometrik untuk dapat memuatkan dompet.",
    "BiometricsNotProvided": "Biometrik tidak disediakan, anda boleh menggunakan PIN untuk memuatkan dompet.",
    "LoggedOut": "Anda telah log keluar",
    "LoggedOutDescription": "Untuk melindungi maklumat anda, anda telah log keluar daripada dompet anda jika anda tidak menggunakannya selama 5 minit.",
    "BiometricsChanged": "Buka kunci biometrik telah dilumpuhkan kerana biometrik peranti anda berubah.",
    "BiometricsChangedEnterPIN": "Sila masukkan PIN dompet anda.",
    "AttemptLockoutWarning": "Nota: untuk keselamatan anda, memasukkan PIN lain yang salah akan mengunci dompet buat sementara waktu."
  },
  "AttemptLockout": {
    "Title": "Dompet anda dikunci buat sementara waktu",
    "Description": "Anda telah mengalami terlalu banyak percubaan PIN yang tidak berjaya.",
    "TryAgain": "Anda boleh mencuba lagi dalam:",
    "Hours": "jam",
    "Minutes": "minit",
    "Seconds": "detik",
  },
  "Biometry": {
    "Toggle": "Togol Biometrik",
    "EnabledText1": "Buka kunci dompet dengan biometrik telefon anda dan bukannya PIN dompet anda.",
    "EnabledText2": "Menggunakan biometrik bermakna semua cap jari atau ID muka yang ditambahkan pada telefon ini akan mempunyai akses kepada dompet anda.",
    "NotEnabledText1": "Biometrik pada masa ini tidak disediakan pada peranti ini dan oleh itu tidak boleh didayakan.",
    "NotEnabledText2": "Jika anda ingin mendayakan ciri ini hidupkan biometrik dalam tetapan peranti dan kemudian kembali ke skrin ini.",
    "Warning": "Pastikan hanya anda yang mempunyai akses kepada dompet anda.",
    "UseToUnlock": "Gunakan biometrik untuk membuka kunci dompet?",
    "UnlockPromptTitle": "Buka Kunci Dompet",
    "UnlockPromptDescription": "Gunakan biometrik untuk membuka kunci dompet anda"
  },
  "Contacts": {
    "EmptyList": "Dompet anda kosong. Kenalan anda yang disambungkan akan ditambahkan di sini.",
    "TypeHere": "Taip Mesej Di Sini",
  },
  "ContactDetails": {
    "Created": "Dicipta",
    "ConnectionState": "Keadaan Sambungan",
    "AContact": "Seorang kenalan",
  },
  "Credentials": {
    "CredentialsNotFound": "Bukti kelayakan tidak ditemui",
    "CredentialDetails": "Butiran Tauliah",
    "EmptyList": "Dompet anda kosong. Bukti kelayakan anda yang diterima akan ditambahkan di sini.",
  },
  "CredentialDetails": {
    "Id": "Id:",
    "CreatedAt": "Dicipta Pada:",
    "Version": "Versi",
    "Issued": "Dikeluarkan",
    "PrivacyPolicy": "Dasar privasi",
    "TermsAndConditions": "Terma dan syarat",
    "RemoveFromWallet": "Alih keluar daripada Wallet",
    "Revoked": "Dibatalkan",
    "CredentialRevokedMessageTitle": "Dibatalkan Pada ",
    "CredentialRevokedMessageBody": "Bukti kelayakan ini mungkin tidak lagi berfungsi untuk beberapa permintaan bukti. Anda perlu mengemas kini bukti kelayakan dengan pengeluar.",
    "NewRevoked": "Tauliah Telah Dibatalkan",
    "RemoveTitle": "Alih keluar kelayakan daripada dompet anda",
    "RemoveCaption": "Anda akan kehilangan keupayaan anda untuk membuktikan maklumat tentang kelayakan ini dengan Wallet ini.",
    "CredentialNotFound": "Bukti kelayakan tidak ditemui",
    "YouWillNotLose": "Anda TIDAK akan rugi",
    "YouWillNotLoseListItem1": "Bukti kelayakan anda dalam sistem yang mengeluarkan bukti kelayakan anda.",
    "YouWillNotLoseListItem2": "Organisasi penerbit sebagai Kenalan.",
    "HowToGetThisCredentialBack": "Bagaimana untuk mendapatkan semula kelayakan ini",
    "HowToGetThisCredentialBackListItem1": "Anda perlu pergi ke organisasi yang mengeluarkan kelayakan ini kepada anda dan memintanya sekali lagi.",
    "CredentialRemoved": "Bukti Kelayakan Berjaya Dialih Keluar",
    "IssuedBy": "Dikeluarkan oleh:"
  },
  "Home": {
    "Welcome": "Selamat datang",
    "WelcomeNext": "  ke SSI Wallet",
    "Notification": "Pemberitahuan",
    "Notifications": "Pemberitahuan",
    "OneNotification": "1 Pemberitahuan",
    "CountNotifications": "{{ count }} Pemberitahuan",
    "NoNewUpdates": "Anda tiada pemberitahuan baharu.",
    "NoCredentials": "Anda tidak mempunyai bukti kelayakan dalam dompet anda.",
    "SeeAll": "Lihat semua",
    "YouHave": "Kamu ada",
    "Credential": "tauliah",
    "Credentials": "kelayakan",
    "InYourWallet": "dalam dompet anda"
  },
  "Scan": {
    "SuccessfullyAcceptedConnection": "Sambungan Berjaya Diterima",
    "AcceptingConnection": "Menerima Sambungan",
    "ConnectionRecordIdNotFound": "ID rekod sambungan tidak ditemui",
    "ConnectionAccepted": "Sambungan Diterima",
    "ConnectionNotFound": "Sambungan tidak ditemui",
    "InvalidQrCode": "Kod QR tidak sah. Sila cuba lagi.",
    "UnableToHandleRedirection": "Tidak dapat mengendalikan ubah hala",
    "Close": "Tutup",
    "Torch": "Kilat"
  },
  "Connection": {
    "JustAMoment": "Sekejap sahaja kami membuat sambungan selamat...",
    "TakingTooLong": "Ini mengambil masa lebih lama daripada biasa. Anda boleh pulang ke rumah atau terus menunggu."
  },
  "ConnectionAlert": {
    "AddedContacts": "Ditambah pada Kenalan",
    "WhatAreContacts": "Apakah itu Kenalan?",
    "NotificationBodyUpper": "Awak boleh cari ",
    "NotificationBodyLower": " dalam Kenalan anda. Urus Kenalan anda dalam Tetapan",
    "PopupIntro": "Menambah organisasi sebagai kenalan akan membolehkan anda melakukannya:",
    "PopupPoint1": "Dapatkan kemas kini pada bukti kelayakan yang dikeluarkan oleh organisasi ini",
    "PopupPoint2": "Dapatkan tawaran kelayakan baharu",
    "PopupPoint3": "Permintaan bukti pantas",
    "SettingsLink": "Tetapan",
    "SettingsInstruction": "Anda sentiasa boleh mengalih keluar kenalan pada bila-bila masa",
    "PrivacyMessage": "Penggunaan bukti kelayakan anda tidak pernah dikongsi dengan kenalan anda.",
    "PopupExit": "Faham"
  },
  "CredentialOffer": {
    "CredentialOffer": "Tawaran Tauliah",
    "ThisIsTakingLongerThanExpected": "Ini mengambil masa Lebih lama daripada jangkaan. Semak semula kemudian untuk bukti kelayakan baharu anda.",
    "RejectThisCredential?": "Tolak Tauliah ini?",
    "AcceptingCredential": "Menerima Tauliah",
    "SuccessfullyAcceptedCredential": "Berjaya Diterima Tauliah",
    "RejectingCredential": "Menolak Tauliah",
    "SuccessfullyRejectedCredential": "Berjaya Menolak Tauliah",
    "CredentialNotFound": "Bukti kelayakan tidak ditemui",
    "CredentialAccepted": "Tauliah Diterima",
    "CredentialRejected": "Tauliah Ditolak",
    "CredentialAddedToYourWallet": "Bukti kelayakan ditambahkan pada dompet anda",
    "CredentialDeclined": "Bukti kelayakan ditolak",
    "CredentialOnTheWay": "Bukti kelayakan anda sedang dalam perjalanan",
    "NewCredentialOffer": "Tawaran Kelayakan Baharu",
    "IsOfferingYouACredential": "sedang menawarkan anda kelayakan",
    "ConfirmDeclinedTitle": "Adakah anda pasti mahu menolak kelayakan ini?",
    "ConfirmDeclinedMessage": "Untuk menerima tawaran kelayakan sekali lagi, anda perlu memohon semula dengan pengeluar.",
    "ConfirmDecline": "Ya, tolak kelayakan ini",
    "AbortDecline": "Tidak, balik",
    "DeclineTitle": "Tolak Tauliah",
  },
  "ProofRequest": {
    "ProofRequest": "Permintaan Bukti",
    "OfferDelay": "Kelewatan tawaran",
    "RejectThisProof?": "Tolak Permintaan Bukti ini?",
    "DeclineThisProof?": "Tolak Permintaan Bukti ini?",
    "AcceptingProof": "Menerima Bukti",
    "SuccessfullyAcceptedProof": "Bukti Berjaya Diterima",
    "ProofRequestNotFound": "Permintaan bukti tidak Ditemui",
    "RejectingProof": "Menolak Bukti",
    "ProofAccepted": "Bukti Diterima",
    "ProofRejected": "Bukti Ditolak",
    "RequestedCredentialsCouldNotBeFound": "Bukti kelayakan yang diminta tidak dapat ditemui",
    "NewProofRequest": "Permintaan Bukti Baharu",
    "NotAvailableInYourWallet": "Data Tidak Tersedia dalam Dompet Anda",
    "IsRequesting": "sedang meminta",
    "IsRequestingSomethingYouDontHaveAvailable": "sedang meminta sesuatu yang anda tidak ada",
    "IsRequestingYouToShare": "sedang meminta anda untuk berkongsi",
    "WhichYouCanProvideFrom": "yang anda boleh sediakan daripada",
    "Details": "Butiran",
    "SendingTheInformationSecurely": "Menghantar maklumat dengan selamat",
    "InformationSentSuccessfully": "Maklumat Berjaya Dihantar",
    "ProofRequestCompleted": "Maklumat diterima",
    "ProofRequestDeclined": "Permintaan Bukti Ditolak",
    "ConfirmDeclinedTitle": "Adakah anda pasti mahu menolak permintaan bukti ini?",
    "ConfirmDeclinedMessage": "Untuk menerima permintaan bukti sekali lagi, peminta perlu menghantarnya semula.",
    "ConfirmDecline": "Ya, Tolak Permintaan Bukti",
    "AbortDecline": "Tidak, balik",
    "DeclineTitle": "Bukti Tolak",
  },
  "Settings": {
    "VersionString": "0.0.0-0",
    "AppSettings": "Tetapan Apl",
    "AboutApp": "Perihal App",
    "Build": "Bina",
    "WhatAreContacts": "Apakah itu Kenalan?",
    "Help": "Tolong",
    "MoreInformation": "Maklumat lanjut",
    "Developer": "Pemaju",
    "ProfileLogin": "Profil & Log Masuk",
    "EditProfile": "Sunting profil",
    "AppPreferences": "Keutamaan Apl",
    "Language": "Bahasa",
    "General": "Umum",
    "AboutUs": "Tentang kita",
    "UserManual": "        Panduan pengguna",
    "SendFeedback": "      Hantar maklumbalas",
    "TermsConditions": "Terma & Syarat",
    "Version": "Versi",
    "VersionNumber": "1.0-1",
  },
  "TabStack": {
    "Home": "Rumah",
    "Scan": "Imbas",
    "Credentials": "Tauliah",
  },
  "RootStack": {
    "Contacts": "Kenalan",
    "Settings": "Tetapan"
  },
  "QRScanner": {
    "PermissionToUseCamera": "Kebenaran untuk menggunakan kamera",
    "WeNeedYourPermissionToUseYourCamera": "Kami memerlukan kebenaran anda untuk menggunakan kamera anda",
    "Ok": "Okey",
  },
  "Record": {
    "Hide": "Sembunyi",
    "Show": "Tunjukkan",
    "HideAll": "Sembunyikan semua",
    "Hidden": "Tersembunyi",
    "InvalidDate": "Tarikh Tidak Sah: "
  },
  "ScanQr": {
    "PlaceCodeInsideBox": "Letakkan kod di dalam kotak.",
    "QrScanHelp": "Perlukan bantuan ?",
  },
  "Screens": {
    "Splash": 'Percikan',
    "Onboarding": "SSI Wallet",
    "Terms": "Terma & Syarat",
    "CreatePin": 'Buat PIN',
    "EnterPin": 'Masukkan PIN',
    "Home": 'Rumah',
    "Scan": 'Imbas',
    "Credentials": 'Tauliah',
    "CredentialDetails": 'Butiran Tauliah',
    "Notifications": 'Pemberitahuan',
    "CredentialOffer": 'Tawaran Tauliah',
    "ProofRequest": 'Permintaan Bukti',
    "ProofRequestAttributeDetails": 'Butiran Atribut Permintaan Bukti',
    "Settings": 'Tetapan',
    "Language": 'Bahasa',
    "Contacts": 'Kenalan',
    "Decline": "Tolak",
    "ContactDetails": 'Butiran kenalan',
    "Biometry": "Biometrik",
    "Developer": "Pemaju",
    "ChangePin": "Tukar PIN",
    "CommonDecline": "Tolak",
    "EditProfile": "Sunting profil",
    "AboutUs" : "Tentang kita",
    "UserManual" : "Panduan pengguna",
    "SendFeedback" : "Hantar maklumbalas",
    "TermsConditions" : "Terma & Syarat",
  },
  "Loading": {
    "TakingTooLong": "Ini mengambil masa lebih lama daripada biasa. Anda boleh pulang ke rumah atau terus menunggu.",
    "BackToHome": "Balik rumah"
  },
  "NetInfo": {
    "NoInternetConnectionTitle": "Tiada Sambungan Internet Dikesan",
    "NoInternetConnectionMessage": "Anda tidak dapat mengakses perkhidmatan atau menerima bukti kelayakan melalui SSI Wallet sehingga anda kembali dalam talian.\n\nSila semak Sambungan Internet anda."
  },
  "LoginRegisterChoiceRegister": {
    "AppTitle": "SSI Wallet",
    "AppDescript": "Trust, Privacy and Verifiability",
    "AppRegister": "Daftar"
  },
  "LoginRegisterChoice": {
    "AppTitle": "SSI Wallet",
    "AppDescript": "Trust, Privacy and Verifiability",
    "AppLogin": "Log Masuk"
  },
  "OnboardingText": {
    "Welcome": "Selamat datang ke SSI Wallet",
    "Page1Line1": "SSI Wallet membolehkan anda Menerima, Menggunakan dan Menyimpan Bukti Kelayakan Digital.",
    "Page1Line2": "Ia menyediakan ciri yang sangat selamat untuk melindungi privasi anda dalam talian.",
    "Page1Line3": "SSI Wallet menampilkan teknologi terkini. Pengguna akan mendapat pengalaman hebat semasa menggunakan SSI Wallet.",
    "Page2Head": "Bukti Kelayakan Digital, Disimpan Dengan Selamat",
    "Page2Line1": "SSI Wallet memegang Bukti Kelayakan Digital yang merangkumi versi digital perkara seperti Identiti, Permit dan Lesen.",
    "Page2Line2": "Ia disimpan dengan selamat, Hanya pada Peranti Ini.",
    "Page3Head": "Menerima dan Menggunakan Tauliah",
    "Page3Line1": "Untuk menerima dan menggunakan bukti kelayakan digital, anda menggunakan ciri 'Imbas' dalam apl untuk mengimbas Kod QR khas.",
    "Page3Line2": "Maklumat dihantar dan diterima melalui sambungan peribadi dan disulitkan.",
    "Page4Head": "Privasi dan Kerahsiaan",
    "Page4Line1": "Anda meluluskan setiap penggunaan maklumat daripada SSI Wallet anda. Anda juga hanya berkongsi apa yang diperlukan untuk sesuatu situasi.",
    "Page4Line2": "Pembangun SSI Wallet tidak diberitahu apabila anda menggunakan bukti kelayakan digital anda.",
  },
  "TermPageInfo": {
    "TermAgreeInfo": "Sila bersetuju dengan terma dan syarat di bawah sebelum menggunakan aplikasi ini.",
    "AppTitle": "The SSI Wallet App",
    "AppText1": "Perjanjian Lesen Pengguna Akhir (“EULA”) ini ialah perjanjian undang-undang antara Anda (“Pemegang Lesen”, “Anda”) sebagai pengguna (sama ada individu atau entiti) ",
    "AppText1a": "https://www.tarc.edu.my/ ",
    "AppText1b": "dan aplikasi mudah alih dan lain-lain yang berkaitan dan Wallet Services Limited, entiti undang-undang yang bertindak dan diperbadankan di bawah undang-undang Malaysia.",
    "HighlightText": "Dengan menunjukkan bahawa anda bersetuju dengan EULA ini, dan sebagai pertimbangan penggunaan Aplikasi Berlesen, anda bersetuju dengan perkara berikut.",
    "Term1": "DENGAN MEMASANG, MENYALIN DAN LAINNYA MENGGUNAKAN PERISIAN DAN IP ANDA MENERIMA SYARAT EULA INI BERKAITAN PERISIAN DAN IP. JIKA ANDA TIDAK MENERIMA SYARAT INI, ANDA TIDAK DIBENARKAN UNTUK MENGGUNAKAN PERISIAN DAN IP.",
    "Term2": "Pemberi Lesen boleh memberikan kepada Anda atau menyediakan kepada Anda Kemas Kini selepas tarikh Anda memperoleh salinan awal Perisian Anda untuk menambah baik Perisian tersebut atau akhirnya meningkatkan pengalaman pengguna Anda dengan Wallet. EULA ini terpakai kepada semua dan mana-mana komponen Kemas Kini yang Pemberi Lesen mungkin berikan kepada Anda atau sediakan kepada Anda selepas Anda memperoleh salinan awal Perisian Anda, melainkan kami menyediakan syarat lain bersama-sama dengan Kemas Kini tersebut. Takrif 'Kemas Kini' merujuk kepada semua kemas kini, naik taraf, tambahan dan komponen tambahan (jika ada) Perisian dan IP, termasuk pembetulan pepijat, naik taraf perkhidmatan (sebahagian atau keseluruhan), produk atau peranti dan kemas kini dan peningkatan kepada sebarang Perisian yang dipasang sebelum ini (termasuk versi baharu sepenuhnya). Untuk menggunakan Perisian yang disediakan melalui Kemas Kini, Anda mesti terlebih dahulu dilesenkan untuk Perisian yang dikenal pasti oleh Pemberi Lesen sebagai layak untuk Kemas Kini. Versi Perisian yang dikemas kini mungkin menambah fungsi baharu dan, dalam beberapa kes terhad, boleh memadamkan fungsi sedia ada.",
    "Term3": "Sebarang pertikaian, kontroversi, perbezaan atau tuntutan yang timbul daripada atau berkaitan dengan Terma, termasuk kewujudan, kesahihan, tafsiran, prestasi, pelanggaran atau penamatannya atau sebarang pertikaian mengenai kewajipan bukan kontrak yang timbul daripada atau berkaitan dengannya hendaklah dirujuk kepada dan akhirnya diselesaikan melalui timbang tara yang ditadbir oleh Pusat Timbang Tara Antarabangsa Hong Kong (HKIAC) di bawah Peraturan Timbang Tara Ditadbir HKIAC yang berkuat kuasa apabila Notis Timbang Tara diserahkan.",
  }
}

export default translation
