/* eslint-disable prettier/prettier */
// prettier-ignore
const translation = {
    "Global": {
      "Enter": "进入",
      "Submit": "提交",
      "NoneYet!": "还没有!",
      "Cancel": "取消",
      "Confirm": "确认",
      "Accept": "接受",
      "Reject": "拒绝",
      "Share": "分享",
      "Decline": "衰退",
      "Back": "后退",
      "Next": "下一个",
      "Continue": "继续",
      "Info": "信息",
      "ThisDecisionCannotBeChanged.": "这个决定不能改变.",
      "Failure": "失败",
      "Success": "成功",
      "SomethingWentWrong": "出问题了",
      "Done": "完毕",
      "Skip": "跳过",
      "View": "看法",
      "Home": "家",
      "ErrorCode": "错误代码",
      "Okay": "好的",
      "GoBack": "回去",
      "GetStarted": "开始",
      "Dismiss": "解雇",
      "ShowDetails": "显示详细资料",
      "TryAgain": "再试一次",
      "Biometrics": "生物识别",
      "On" : "开",
      "Off": "关",
    },
    "Language": {
      "English": "英语",
      "Melayu": "马来语",
      "Chinese": "华语",
    },
    "Error": {
      "Unknown": "未知错误",
      "Problem": "出现问题",
      "ErrorCode": "错误代码",
      "Title1024": "无法接受凭证提供.",
      "Message1024": "There was a problem while accepting the Credential Offer.",
      "Title1025": "Unable to Reject Credential Offer",
      "Message1025": "There was a problem while Rejecting the Credential Offer",
      "Title1026": "Unable to update Retrieved Credentials.",
      "Message1026": "There was a problem while updating Retrieved Credentials.",
      "Title1027": "Unable to Accept Proof Request.",
      "Message1027": "There was a problem while accepting the Proof Request.",
      "Title1028": "Unable to Reject Proof Request",
      "Message1028": "There was a problem while Rejecting the Proof Request",
      "Title1029": "Details	Unable to Update Retrieved Credentials.",
      "Message1029": "There was a problem while updating Retrieved Credentials.",
      "Title1030": "Unable to Accept Connection.",
      "Message1030": "There was a problem while accepting the Connection Redirection.",
      "Title1031": "Unable to Accept Connection.",
      "Message1031": "There was a problem while Accepting the Connection.",
      "Title1032": "Unable to Remove Credential.",
      "Message1032": "There was a problem while Removing the Credential.",
      "Title1033": "Unable to Fetch Credential.",
      "Message1033": "Credential could not be found.",
      "Title1034": "Unable to fetch Proof Request.",
      "Message1034": "Proof Request could not be found.",
      "Title1035": "Unable to fetch Credential Offer.",
      "Message1035": "Credential Offer could not be found.",
      "Title1036": "Unable to fetch Wallet Credentials",
      "Message1036": "Wallet Credentials could not be found",
    },
    "StatusMessages": {
      "InitAgent": "Initializing Agent .."
    },
    "Terms": {
      "TermsOfService": "Terms of Service",
      "TermsOfServiceText": ".",
      "IAgree": "I Agree",
      "Attestation": "I have read, understand and accept the Terms and Conditions.",
    },
    "PrivacyPolicy": {
      "Title": "Privacy Policy",
      "CameraDisclosure": "The camera is used to scan QR Codes for immediate on-device processing. No information about the images is stored, used for analytics, or shared.",
    },
    "PinCreate": {
      "Message": {
        "CrossPatternValidation": 'A pattern of cross was detected in your PIN. Please Try Again.',
        "OddOrEvenSequenceValidation": 'An odd or even sequence was detected in your PIN. Please Try Again.',
        "NoRepetitionOfTheSameNumbersValidation":
          "The PIN can't have a repetition of the same digit. Please Try Again.",
        "NoRepetitionOfTheTwoSameNumbersValidation": 'A repeated two-digit sequence was detected in your PIN. Please Try Again.',
        "NoSeriesOfNumbersValidation": 'A series was detected in your PIN. Please Try Again.',
        "PinOnlyContainDigitsValidation": 'Your PIN needs to only contain digits. Please Try Again.',
        "PinTooShortValidation": 'Your PIN is too short. Please Try Again.',
        "PinTooLongValidation": 'Your PIN is too long. Please Try Again.',
      },
      "Helper": {
        "CrossPatternValidation": 'Does not contain a pattern of cross.',
        "OddOrEvenSequenceValidation": 'Does not contain an odd or even sequence.',
        "NoRepetitionOfTheSameNumbersValidation": 'Does not contain the same repeating number.',
        "NoRepetitionOfTheTwoSameNumbersValidation": 'Does not contain repeating two-digit sequence.',
        "NoSeriesOfNumbersValidation": 'Does not contain a series of numbers (123).',
        "PinOnlyContainDigitsValidation": 'Must contain only digits.',
        "PinTooShortValidation": 'The PIN is long enoughs.',
        "PinTooLongValidation": 'The PIN is long enoughs.',
      },
      "UserAuthenticationPIN": "User authentication PIN",
      "PINTooShort": "PIN is too short",
      "InvalidPIN": "Invalid PIN",
      "PINsDoNotMatch": "PIN Not Match",
      "PleaseUseOnlyNumbersInYourPIN": "Please use only numbers in your PIN",
      "YourPINMustBe6DigitsInLength": "Your PIN needs to be 6 digits long.",
      "EnteredPINsDoNotMatch": "The entered PINs do not match. Please Try Again.",
      "YouNeedToCreateA6DigitPIN": "You need to create a 6 digit PIN",
      "PleaseReenterYourPIN": "Please re-enter your PIN",
      "EnterPINTitle": "Enter a 6 digit PIN",
      "EnterPIN": "Enter PIN",
      "ReenterPIN": "Confirm PIN",
      "ReenterPINTitle": "Re-Enter PIN",
      "CreatePIN": "Create PIN",
      "RememberPIN": "Remember your PIN.",
      "PINDisclaimer": "If you forget it, you will need to set up your wallet again and re-add your cards.",
      "Show": "Show PIN",
      "Hide": "Hide PIN",
      "ChangePIN": "Change PIN",
      "Continue": "Continue",
      "EnterYourCurrentPIN": "Enter your current PIN"
    },
    "PinEnter": {
      "EnterPIN": "Enter your wallet PIN",
      "Unlock":"Unlock",
      "Or":"Or",
      "BiometricsUnlock": "Unlock with Biometrics",
      "IncorrectPIN": "Incorrect PIN",
      "RepeatPIN": "Please Re-enter your PIN.",
      "EnableBiometrics": "You have to enable biometrics to be able to load the wallet.",
      "BiometricsNotProvided": "Biometrics not provided, you may use PIN to load the wallet.",
      "LoggedOut": "You're logged out",
      "LoggedOutDescription": "To protect your information, you're logged out of your wallet if you have not used it for 5 minutes.",
      "BiometricsChanged": "Biometrics unlock has been disabled because your device biometrics changed.",
      "BiometricsChangedEnterPIN": "Please enter your wallet PIN.",
      "AttemptLockoutWarning": "Note: for your security, entering another incorrect PIN will temporarily lock the wallet."
    },
    "AttemptLockout": {
      "Title": "Your wallet is temporarily locked",
      "Description": "You have had too many unsuccessful PIN attempts.",
      "TryAgain": "You can try again in:",
      "Hours": "hours",
      "Minutes": "minutes",
      "Seconds": "seconds",
    },
    "Biometry": {
      "Toggle": "Toggle Biometrics",
      "EnabledText1": "Unlock the wallet with your phone's biometrics instead of your wallet PIN.",
      "EnabledText2": "Using biometrics means that all fingerprints or face ID added on this phone will have access to your wallet.",
      "NotEnabledText1": "Biometrics is not currently setup on this device and therefore cannot be enabled.",
      "NotEnabledText2": "If you wish to enable this feature turn biometrics on in the device settings and then return to this screen.",
      "Warning": "Ensure only you have access to your wallet.",
      "UseToUnlock": "Use biometrics to unlock wallet?",
      "UnlockPromptTitle": "Wallet Unlock",
      "UnlockPromptDescription": "Use biometrics to unlock your wallet"
    },
    "Contacts": {
      "EmptyList": "Your wallet is empty. Your connected contacts will be added here.",
      "TypeHere": "Type Message Here",
    },
    "ContactDetails": {
      "Created": "Created",
      "ConnectionState": "Connection State",
      "AContact": "A contact",
    },
    "Credentials": {
      "CredentialsNotFound": "Credentials not found",
      "CredentialDetails": "Credential Details",
      "EmptyList": "Your wallet is empty. Your accepted credentials will be added here.",
    },
    "CredentialDetails": {
      "Id": "Id:",
      "CreatedAt": "Created At:",
      "Version": "Version",
      "Issued": "Issued",
      "PrivacyPolicy": "Privacy policy",
      "TermsAndConditions": "Terms and conditions",
      "RemoveFromWallet": "Remove from Wallet",
      "Revoked": "Revoked",
      "CredentialRevokedMessageTitle": "Revoked On ",
      "CredentialRevokedMessageBody": "This credential may no longer work for some proof requests. You will need to update the credential with the issuer.",
      "NewRevoked": "Credential Was Revoked",
      "RemoveTitle": "Remove credential from your wallet",
      "RemoveCaption": "You will lose your ability to prove the information on this credential with this Wallet.",
      "CredentialNotFound": "Credential not found",
      "YouWillNotLose": "You will NOT lose",
      "YouWillNotLoseListItem1": "Your credential within the system that issued you your credential.",
      "YouWillNotLoseListItem2": "The issuing organization as a Contact.",
      "HowToGetThisCredentialBack": "How to get this credential back",
      "HowToGetThisCredentialBackListItem1": "You will have to go to the organization that issued you this credential and request it again.",
      "CredentialRemoved": "Credential Removed Successfully",
      "IssuedBy": "Issued by:"
    },
    "Home": {
      "Welcome": "    Welcome",
      "WelcomeNext": " to SSI Wallet",
      "Notification": "Notification",
      "Notifications": "Notifications",
      "OneNotification": "1 Notification",
      "CountNotifications": "{{ count }} Notifications",
      "NoNewUpdates": "You have no new notifications.",
      "NoCredentials": "You have no credentials in your wallet.",
      "SeeAll": "See all",
      "YouHave": "You have",
      "Credential": "credential",
      "Credentials": "credentials",
      "InYourWallet": "in your wallet"
    },
    "Scan": {
      "SuccessfullyAcceptedConnection": "Successfully Accepted Connection",
      "AcceptingConnection": "Accepting Connection",
      "ConnectionRecordIdNotFound": "Connection record ID not found",
      "ConnectionAccepted": "Connection Accepted",
      "ConnectionNotFound": "Connection not found",
      "InvalidQrCode": "Invalid QR code. Please Try Again.",
      "UnableToHandleRedirection": "Unable to handle redirection",
      "Close": "Close",
      "Torch": "Flash"
    },
    "Connection": {
      "JustAMoment": "Just a moment while we make a secure connection...",
      "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting."
    },
    "ConnectionAlert": {
      "AddedContacts": "Added to Contacts",
      "WhatAreContacts": "What are Contacts?",
      "NotificationBodyUpper": "You can find ",
      "NotificationBodyLower": " in your Contacts. Manage your Contacts in Settings",
      "PopupIntro": "Adding organizations as a contact will allow you to:",
      "PopupPoint1": "Get updates to credentials issued by this organization",
      "PopupPoint2": "Get offered new credentials",
      "PopupPoint3": "Fast-track proof requests",
      "SettingsLink": "Settings",
      "SettingsInstruction": "You can always remove contacts at anytime",
      "PrivacyMessage": "Use of your credentials is never shared with your contacts.",
      "PopupExit": "Got it"
    },
    "CredentialOffer": {
      "CredentialOffer": "Credential Offer",
      "ThisIsTakingLongerThanExpected": "This is taking Longer than expected. Check back later for your new credential.",
      "RejectThisCredential?": "Reject this Credential?",
      "AcceptingCredential": "Accepting Credential",
      "SuccessfullyAcceptedCredential": "Successfully Accepted Credential",
      "RejectingCredential": "Rejecting Credential",
      "SuccessfullyRejectedCredential": "Successfully Rejected Credential",
      "CredentialNotFound": "Credential not found",
      "CredentialAccepted": "Credential Accepted",
      "CredentialRejected": "Credential Rejected",
      "CredentialAddedToYourWallet": "Credential added to your wallet",
      "CredentialDeclined": "Credential declined",
      "CredentialOnTheWay": "Your credential is on the way",
      "NewCredentialOffer": "New Credential Offer",
      "IsOfferingYouACredential": "is offering you a credential",
      "ConfirmDeclinedTitle": "Are you sure you want to decline this credential?",
      "ConfirmDeclinedMessage": "In order to receive the credential offer again, you will need to reapply with the issuer.",
      "ConfirmDecline": "Yes, decline this credential",
      "AbortDecline": "No, go back",
      "DeclineTitle": "Decline Credential",
    },
    "ProofRequest": {
      "ProofRequest": "Proof Request",
      "OfferDelay": "Offer delay",
      "RejectThisProof?": "Reject this Proof Request?",
      "DeclineThisProof?": "Decline this Proof Request?",
      "AcceptingProof": "Accepting Proof",
      "SuccessfullyAcceptedProof": "Successfully Accepted Proof",
      "ProofRequestNotFound": "Proof request not Found",
      "RejectingProof": "Rejecting Proof",
      "ProofAccepted": "Proof Accepted",
      "ProofRejected": "Proof Rejected",
      "RequestedCredentialsCouldNotBeFound": "Requested credentials could not be found",
      "NewProofRequest": "New Proof Request",
      "NotAvailableInYourWallet": "Data Not Available in Your Wallet",
      "IsRequesting": "is requesting",
      "IsRequestingSomethingYouDontHaveAvailable": "is requesting something you don't have available",
      "IsRequestingYouToShare": "is requesting you to share",
      "WhichYouCanProvideFrom": "which you can provide from",
      "Details": "Details",
      "SendingTheInformationSecurely": "Sending the information securely",
      "InformationSentSuccessfully": "Information Sent Successfully",
      "ProofRequestCompleted": "Information received",
      "ProofRequestDeclined": "Proof Request Declined",
      "ConfirmDeclinedTitle": "Are you sure you want to decline this proof request?",
      "ConfirmDeclinedMessage": "In order to receive the proof request again, the requestor will need to resend it.",
      "ConfirmDecline": "Yes, Decline The Proof Request",
      "AbortDecline": "No, go back",
      "DeclineTitle": "Decline Proof",
    },
    "Settings": {
      "VersionString": "0.0.0-0",
      "AppSettings": "App Settings",
      "AboutApp": "About App",
      "Build": "Build",
      "WhatAreContacts": "What are Contacts?",
      "Help": "Help",
      "MoreInformation": "More information",
      "Developer": "Developer",
      "ProfileLogin": "Profile & Login",
      "EditProfile": "Edit Profile",
      "AppPreferences": "App Preferences",
      "Language": "Language",
      "General": "General",
      "AboutUs": "About Us",
      "UserManual": "User Manual",
      "SendFeedback": "Send Feedback",
      "TermsConditions": "Terms & Conditions",
      "Version": "Version",
      "VersionNumber": "1.0-1",
    },
    "TabStack": {
      "Home": "Home",
      "Scan": "Scan",
      "Credentials": "Credentials",
    },
    "RootStack": {
      "Contacts": "Contacts",
      "Settings": "Settings"
    },
    "QRScanner": {
      "PermissionToUseCamera": "Permission to use camera",
      "WeNeedYourPermissionToUseYourCamera": "We need your permission to use your camera",
      "Ok": "Ok",
    },
    "Record": {
      "Hide": "Hide",
      "Show": "Show",
      "HideAll": "Hide all",
      "Hidden": "Hidden",
      "InvalidDate": "Invalid Date: "
    },
    "ScanQr": {
      "PlaceCodeInsideBox": "Place code inside the box.",
      "QrScanHelp": "Need Help ?",
    },
    "Screens": {
      "Splash": 'Splash',
      "Onboarding": "SSI Wallet",
      "Terms": "Terms & Conditions",
      "CreatePin": 'Create a PIN',
      "EnterPin": 'Enter PIN',
      "Home": 'Home',
      "Scan": 'Scan',
      "Credentials": 'Credentials',
      "CredentialDetails": 'Credential Details',
      "Notifications": 'Notifications',
      "CredentialOffer": 'Credential Offer',
      "ProofRequest": 'Proof Request',
      "ProofRequestAttributeDetails": 'Proof Request Attribute Details',
      "Settings": 'Settings',
      "Language": 'Language',
      "Contacts": 'Contacts',
      "Decline": "Decline",
      "ContactDetails": 'Contact Details',
      "Biometry": "Biometrics",
      "Developer": "Developer",
      "ChangePin": "Change PIN",
      "CommonDecline": "Decline",
      "EditProfile": "Edit Profile",
      "AboutUs" : "About Us",
      "UserManual" : "User Manual",
      "SendFeedback" : "Send Feedback",
      "TermsConditions" : "Terms & Conditions",
    },
    "Loading": {
      "TakingTooLong": "This is taking longer than usual. You can return to home or continue waiting.",
      "BackToHome": "Go back to home"
    },
    "NetInfo": {
      "NoInternetConnectionTitle": "No Internet Connection Detected",
      "NoInternetConnectionMessage": "You're unable to access services or receive credentials via SSI Wallet until you're back online.\n\nPlease check your Internet Connection."
    },
    "LoginRegisterChoiceRegister": {
      "AppTitle": "SSI Wallet",
      "AppDescript": "Trust, Privacy and Verifiability",
      "AppRegister": "Register"
    },
    "LoginRegisterChoice": {
      "AppTitle": "SSI Wallet",
      "AppDescript": "Trust, Privacy and Verifiability",
      "AppLogin": "Login"
    },
    "OnboardingText": {
      "Welcome": "Welcome to SSI Wallet",
      "Page1Line1": "SSI Wallet lets you Receive, Use and Store Digital Credentials.",
      "Page1Line2": "It provide highly secure feature to protect your privacy online.",
      "Page1Line3": "SSI Wallet is featuring latest technology. User will have a great experience while using the SSI Wallet.",
      "Page2Head": "Digital Credentials, Stored Securely",
      "Page2Line1": "SSI Wallet holds Digital Credentials which include the digital versions of things like Identities, Permits and Licenses.",
      "Page2Line2": "They are stored securely, Only on This Device.",
      "Page3Head": "Receiving and Using Credentials",
      "Page3Line1": "To receive and use digital credentials you use the “Scan” feature in the app to scan a special QR Code.",
      "Page3Line2": "Information is sent and received over a private and encrypted connection.",
      "Page4Head": "Privacy and Confidentiality",
      "Page4Line1": "You approve every use of information from your SSI Wallet. You also only share what is needed for a situation.",
      "Page4Line2": "The Developer of SSI Wallet is not told when you use your digital credentials.",
    },
    "TermPageInfo": {
      "TermAgreeInfo": "Please agree to the terms and conditions below before using this application.",
      "AppTitle": "The SSI Wallet App",
      "AppText1": "This End-User License Agreement (“EULA”) is a legal agreement between You (“Licensee”, “You”) as the user (either an individual or an entity) of ",
      "AppText1a": "https://www.tarc.edu.my/ ",
      "AppText1b": "and its related mobile and other applications and Wallet Services Limited, legal entity acting and incorporated under the laws of Malaysia.",
      "HighlightText": "By indicating that you agree to this EULA, and in consideration of the use of the Licensed Application, you agree to the following.",
      "Term1": "BY INSTALLING, COPYING AND OTHERWISE USING THE SOFTWARE AND THE IP YOU ACCEPT THE TERMS OF THIS EULA REGARDING THE SOFTWARE AND THE IP. IF YOU DO NOT ACCEPT THESE TERMS, YOU ARE NOT PERMITTED TO USE THE SOFTWARE AND THE IP.",
      "Term2": "Licensor may provide to You or make available to You Updates after the date You obtain Your initial copy of the Software in order to improve such Software or ultimately enhance Your user experience with the Wallet. This EULA applies to all and any component of the Update that Licensor may provide to You or make available to You after You obtain Your initial copy of the Software, unless we provide other terms along with such Update. The definition 'Update' refers to all updates, upgrades, supplements and add-on components (if any) of the Software and IP, including bug fixes, service upgrades (partly or entire), products or devices, and updates, and enhancements to any Software previously installed (including entirely new versions). To use the Software provided through Update, You must first be licensed for the Software identified by Licensor as eligible for the Update. The updated Software version may add new functions and, in some limited cases, may delete existing functions.",
      "Term3": "Any dispute, controversy, difference or claim arising out of or relating to the Terms, including the existence, validity, interpretation, performance, breach or termination thereof or any dispute regarding non-contractual obligations arising out of or relating to it shall be referred to and finally resolved by arbitration administered by the Hong Kong International Arbitration Centre (HKIAC) under the HKIAC Administered Arbitration Rules in force when the Notice of Arbitration is submitted.",
    }
  }
  
  export default translation
  